server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssmdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zsl20000315
    driver-class-name: com.mysql.cj.jdbc.Driver
